server:
  port: 9872

spring:
  application:
    name: model-service
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_shop
    username: postgres
    password: 5Potok9-
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetch-registry: true